---
baseURL: https://molware.org/
languageCode: en-us
title: m0lware Cybersecurity Blog
theme: piko
paginate: "9"
copyright: 
googleAnalytics: G-08SNX50RP1
# Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Your Name
  description: Personal Cybersecurity Blog
  math: false
  images:
  - "/uploads/server2.jpg"
  label:
    title: m0lware
    text: Welcome to Piko
    lightNavIcon: /uploads/molware.svg
    darkNavIcon: /uploads/molware.svg
    iconHeight: "80"
    iconWIdth: "80"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction:  https://fabform.io/f/kmpG4ga
  assets:
    disableFingerprinting: false
    favicon: /uploads/molware.svg
    favicon16x16: /uploads/molware.svg
    favicon32x32: /uploads/molware.svg
    apple_touch_icon: /uploads/molware.svg
    safari_pinned_tab: /uploads/molware.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: m0lware 
    heroDescription: Just another cybersecurity blog
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/server2.jpg"
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: These are my latest blog posts
    seeMoreText: More Posts
    # About Section    
    disableAboutSection: true
    # aboutTitle: About
    # aboutDescription: Just something about me
    # aboutImgUrl: "/uploads/self.webp"
    # aboutContent: Hi guys. This is where you put something about yourself.
    # Portfolio Section
    disablePortfolioSection: true
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    # portfolio:
    # - imageUrl: /uploads/portfolio-1.webp
    #   alt: # image alt for better SEO
    #   description: Portfolio One.
    #   websiteUrl: #
    # - imageUrl: /uploads/portfolio-2.webp
    #   alt: # image alt for better SEO
    #   description: Portfolio Two.
    #   websiteUrl: #
    # - imageUrl: /uploads/portfolio-3.webp
    #   alt: # image alt for better SEO
    #   description: Portfolio Three.
    #   websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Calendar
    title: Consult
    pre: calendar
    url: https://calendly.com/molware/consultation
    weight: "50"
  - name: Github
    title: 
    pre: github
    url: https://github.com/molware
    weight: "60"
  - name: Twitter
    title: 
    pre: twitter
    url: https://twitter.com/M0lware
    weight: "70"
  - name: RSS
    title:
    pre: rss
    url: https://molware.org/blog/index.xml
    weight: 80
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
